version: "3.8"

services:
  nginx:
    build:
      context: ./requirements/nginx
      args:
        DOMAIN: ${DOMAIN}
    container_name: nginx
    depends_on:
      - wordpress
    restart: always
    networks:
      - docker-network
    volumes:
      - wp_files:/var/www/wordpress/
    ports:
      - "443:443"
    env_file: .env
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - docker-network
    volumes:
      - wp_files:/var/www/wordpress/
    env_file: .env
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USER_PASSWORD: ${DB_USER_PASSWORD}
        ROOT_PASSWORD: ${ROOT_PASSWORD}
    container_name: mariadb
    restart: always
    networks:
      - docker-network
    volumes:
      - data:/var/lib/mysql/

volumes:
  data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/data"
  wp_files:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/wp_files"

networks:
  docker-network:
    driver: bridge
