CREATE DATABASE IF NOT EXISTS DATABASE_NAME;
GRANT ALL ON *.* TO 'DATABASE_USER' IDENTIFIED BY 'USER_PASSWORD' WITH GRANT OPTION;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'DATABASE_ROOT_PASSWOD';
FLUSH PRIVILEGES;